import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Search, Scale, Landmark } from 'lucide-react';
import { supabase } from '../lib/supabase';
import toast from 'react-hot-toast';

type Sale = { id: string; invoice_date: string; warehouse_code: string; warehouse_name: string; reporting_category: string; category: string; sub_category: string; transaction_type: string; total_tonnes: number; total_sales_amount: number; line_count: number; imported_at: string };
const money = new Intl.NumberFormat(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function SoldTonnagePage() {
  const [rows, setRows] = useState<Sale[]>([]); const [search, setSearch] = useState('');
  const load = async () => { const { data, error } = await supabase.from('sage_sold_tonnage_daily').select('*').order('invoice_date', { ascending: false }).limit(2000); if (error) toast.error(`Could not load Sage sales reporting: ${error.message}`); else setRows((data || []) as Sale[]); };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => rows.filter((r) => `${r.warehouse_code} ${r.warehouse_name} ${r.reporting_category} ${r.category} ${r.transaction_type}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  const tonnes = visible.reduce((sum, r) => sum + Number(r.total_tonnes || 0), 0); const value = visible.reduce((sum, r) => sum + Number(r.total_sales_amount || 0), 0); const reversals = visible.filter((r) => Number(r.total_tonnes) < 0 || Number(r.total_sales_amount) < 0).length;
  return <div className="min-h-[calc(100vh-4rem)] bg-slate-50 p-4 md:p-6"><div className="mx-auto max-w-[1500px] space-y-5">
    <section className="rounded-lg border border-slate-900 bg-slate-900 px-6 py-6 text-white shadow-lg"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-cyan-300"><Landmark className="h-4 w-4" /> Sage reporting</p><h1 className="mt-2 text-2xl font-bold">Sold Tonnage</h1><p className="mt-1 text-sm text-slate-300">Net Branch POS and HQ-invoiced tonnes from the Power BI reporting view.</p></div><p className="text-xs text-slate-400">Read-only Sage data</p></div></section>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Net tonnes sold" value={`${tonnes.toLocaleString(undefined, { maximumFractionDigits: 2 })} t`} icon={<Scale className="h-5 w-5" />} /><Metric label="Net sales value" value={money.format(value)} icon={<Landmark className="h-5 w-5" />} /><Metric label="Credit / reversal rows" value={String(reversals)} icon={<BarChart3 className="h-5 w-5" />} /></div>
    <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-slate-900">Sage sales detail</h2><p className="text-xs text-slate-500">Positive and negative values are retained so totals reconcile to Power BI.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Branch or category" className="rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[940px] text-sm"><thead className="bg-slate-50 text-left text-[11px] font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Branch / warehouse</th><th className="px-4 py-3">Product group</th><th className="px-4 py-3">Channel</th><th className="px-4 py-3 text-right">Tonnes</th><th className="px-4 py-3 text-right">Sales value</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((r) => <tr key={r.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-mono text-xs">{r.invoice_date}</td><td className="px-4 py-3"><p className="font-semibold text-slate-900">{r.warehouse_code || 'HQ'}</p><p className="text-xs text-slate-500">{r.warehouse_name}</p></td><td className="px-4 py-3"><p className="font-semibold">{r.reporting_category || r.category}</p><p className="text-xs text-slate-500">{r.sub_category}</p></td><td className="px-4 py-3">{r.transaction_type}</td><td className={`px-4 py-3 text-right font-mono font-bold ${Number(r.total_tonnes) < 0 ? 'text-rose-700' : 'text-slate-900'}`}>{Number(r.total_tonnes).toLocaleString(undefined, { maximumFractionDigits: 3 })}</td><td className={`px-4 py-3 text-right font-mono ${Number(r.total_sales_amount) < 0 ? 'text-rose-700' : 'text-slate-800'}`}>{money.format(Number(r.total_sales_amount))}</td></tr>)}{!visible.length && <tr><td colSpan={6} className="px-4 py-12 text-center text-slate-400">No Sage sold-tonnage rows have been imported yet.</td></tr>}</tbody></table></div></section>
  </div></div>;
}
function Metric({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between text-slate-500"><p className="text-xs font-bold uppercase tracking-wide">{label}</p>{icon}</div><p className="mt-3 text-2xl font-bold text-slate-900">{value}</p></div>; }
